import { Role, ForumUser, Post } from '../../types/forum';

// ── Roles (mirrors a Role collection referenced by User.role) ──────────────
export const roles: Record<string, Role> = {
  admin:     { id: 'r1', name: 'Administrator', color: '#ef4444', icon: 'shield' },
  moderator: { id: 'r2', name: 'Moderator',      color: '#10b981', icon: 'shield' },
  member:    { id: 'r3', name: 'Member',         color: '#8a8d91', icon: null },
  senior:    { id: 'r4', name: 'Senior Member',  color: '#4b8ef1', icon: 'star' },
};

// ── Full user profiles (mirrors models/User.ts) ────────────────────────────
export const forumUsers: Record<string, ForumUser> = {
  admin: {
    _id: 'u1',
    username: 'Admin',
    avatar: null,
    avatarLetter: 'A',
    signature: 'Keep it civil, keep it useful.',
    bio: 'Running this place since day one.',
    role: roles.admin,
    customTitle: 'Founder',
    postCount: 2140,
    threadCount: 88,
    reputation: 4502,
    joinedAt: '2019-03-01',
    lastSeenAt: '2026-06-16',
    isBanned: false,
    isVerified: true,
    isOnline: true,
    socials: { twitter: 'admin', website: 'nexusforum.example' },
  },
  rustacean: {
    id: 'u2',
    username: 'rustacean',
    avatar: null,
    avatarLetter: 'R',
    signature: 'fn main() { loop { code(); } }',
    bio: 'Systems programmer, Rust evangelist.',
    role: roles.senior,
    customTitle: 'Senior Member',
    postCount: 891,
    threadCount: 34,
    reputation: 1320,
    joinedAt: '2021-07-12',
    lastSeenAt: '2026-06-16',
    isBanned: false,
    isVerified: true,
    isOnline: true,
    socials: { github: 'rustacean' },
  },
  jonah_dev: {
    id: 'u3',
    username: 'jonah_dev',
    avatar: null,
    avatarLetter: 'J',
    signature: '',
    bio: 'Full-stack dev. Mostly Next.js these days.',
    role: roles.moderator,
    customTitle: 'Moderator',
    postCount: 1560,
    threadCount: 61,
    reputation: 2210,
    joinedAt: '2020-11-02',
    lastSeenAt: '2026-06-16',
    isBanned: false,
    isVerified: true,
    isOnline: true,
    socials: { github: 'jonahdev', website: 'jonah.dev' },
  },
  techguru: {
    id: 'u4',
    username: 'techguru',
    avatar: null,
    avatarLetter: 'T',
    signature: 'Benchmarks don\'t lie.',
    bio: '',
    role: roles.member,
    customTitle: '',
    postCount: 412,
    threadCount: 19,
    reputation: 540,
    joinedAt: '2022-02-18',
    lastSeenAt: '2026-06-15',
    isBanned: false,
    isVerified: false,
    isOnline: false,
  },
  newuser99: {
    id: 'u8',
    username: 'newuser99',
    avatar: null,
    avatarLetter: 'N',
    signature: '',
    bio: '',
    role: roles.member,
    customTitle: '',
    postCount: 4,
    threadCount: 1,
    reputation: 2,
    joinedAt: '2026-06-14',
    lastSeenAt: '2026-06-16',
    isBanned: false,
    isVerified: false,
    isOnline: true,
  },
};

// ── Posts, keyed by threadId — shape mirrors the Post schema ───────────────
export const postsByThread: Record<string, Post[]> = {
  t2: [
    {
      id: 'p1',
      threadId: 't2',
      author: forumUsers.rustacean,
      content:
        '<p>Been writing Rust professionally for about three years now and the shift in the systems space is hard to ignore. Memory safety without a GC, fearless concurrency, and a package manager that actually works.</p><p>Curious what others here are seeing in their orgs — are you adopting it for new services, or mostly greenfield?</p>',
      isFirstPost: true,
      isDeleted: false,
      editedAt: null,
      quotedPost: null,
      attachments: [],
      reactionCount: { like: 42, love: 12, haha: 0, wow: 3, sad: 0, angry: 0 },
      createdAt: '2026-06-10T09:12:00Z',
      postNumber: 1,
    },
    {
      id: 'p2',
      threadId: 't2',
      author: forumUsers.jonah_dev,
      content:
        '<p>We moved our auth service to Rust last quarter, mostly greenfield. The compile times were rough at first but <em>tower</em> and <em>axum</em> made the web layer pretty pleasant.</p>',
      isFirstPost: false,
      isDeleted: false,
      editedAt: null,
      quotedPost: {
        id: 'p1',
        author: forumUsers.rustacean,
        contentSnippet:
          'Been writing Rust professionally for about three years now and the shift in the systems space is hard to ignore.',
      },
      attachments: [],
      reactionCount: { like: 18, love: 2, haha: 0, wow: 0, sad: 0, angry: 0 },
      createdAt: '2026-06-10T10:40:00Z',
      postNumber: 2,
    },
    {
      id: 'p3',
      threadId: 't2',
      author: forumUsers.techguru,
      content:
        '<p>Honestly still on the fence. Our team knows Go really well and the productivity gap is real when you\'re shipping fast. <strong>Not</strong> saying Rust isn\'t worth it long-term though.</p>',
      isFirstPost: false,
      isDeleted: false,
      editedAt: '2026-06-10T12:05:00Z',
      editReason: 'Fixed typo',
      quotedPost: null,
      attachments: [],
      reactionCount: { like: 7, love: 0, haha: 1, wow: 0, sad: 0, angry: 0 },
      createdAt: '2026-06-10T11:58:00Z',
      postNumber: 3,
    },
    {
      id: 'p4',
      threadId: 't2',
      author: forumUsers.newuser99,
      content:
        '<p>New to systems programming entirely, is Rust a reasonable first language for this kind of work or should I start with C first to understand what Rust is protecting me from?</p>',
      isFirstPost: false,
      isDeleted: false,
      editedAt: null,
      quotedPost: null,
      attachments: [],
      reactionCount: { like: 5, love: 0, haha: 0, wow: 0, sad: 0, angry: 0 },
      createdAt: '2026-06-16T06:04:00Z',
      postNumber: 4,
    },
  ],
};

export function getPostsForThread(threadId: string): Post[] {
  return postsByThread[threadId] ?? [];
}