import { Thread, SubforumMeta, ThreadUser } from '../../types/forum';

// ── Reusable mock users ─────────────────────────────────────────────────────
const users: Record<string, ThreadUser> = {
  admin:        { id: 'u1', username: 'Admin',        avatar: 'A', role: 'admin' },
  rustacean:    { id: 'u2', username: 'rustacean',     avatar: 'R', role: 'member' },
  jonah_dev:    { id: 'u3', username: 'jonah_dev',     avatar: 'J', role: 'moderator' },
  techguru:     { id: 'u4', username: 'techguru',      avatar: 'T', role: 'member' },
  cinephile:    { id: 'u5', username: 'cinephile',     avatar: 'C', role: 'member' },
  pcmasterrace: { id: 'u6', username: 'pcmasterrace',  avatar: 'P', role: 'member' },
  mobileking:   { id: 'u7', username: 'mobileking',    avatar: 'M', role: 'member' },
  newuser99:    { id: 'u8', username: 'newuser99',     avatar: 'N', role: 'member' },
};

// ── Subforum metadata (id must match Subforum.id used on the home page) ────
export const subforumMeta: Record<string, SubforumMeta> = {
  announcements: {
    id: 'announcements',
    name: 'Announcements',
    description: 'Official news and updates from the staff team.',
    accentColor: '#f59e0b',
  },
  introductions: {
    id: 'introductions',
    name: 'Introductions',
    description: 'New here? Say hello and introduce yourself to the community.',
    accentColor: '#f59e0b',
  },
  programming: {
    id: 'programming',
    name: 'Programming',
    description: 'Discuss languages, frameworks, open source projects and dev tools.',
    accentColor: '#4b8ef1',
  },
  webdev: {
    id: 'webdev',
    name: 'Web Development',
    description: 'Frontend, backend, full-stack, DevOps — all things web.',
    accentColor: '#4b8ef1',
  },
  hardware: {
    id: 'hardware',
    name: 'Hardware & Devices',
    description: 'CPUs, GPUs, peripherals, builds, and everything physical.',
    accentColor: '#4b8ef1',
  },
  offtopic: {
    id: 'offtopic',
    name: 'Off Topic',
    description: "Anything and everything that doesn't fit elsewhere.",
    accentColor: '#10b981',
  },
  media: {
    id: 'media',
    name: 'Movies & TV',
    description: 'Reviews, recommendations, and discussions on films and series.',
    accentColor: '#10b981',
  },
  'pc-gaming': {
    id: 'pc-gaming',
    name: 'PC Gaming',
    description: 'PC game recommendations, builds, mods, and gaming news.',
    accentColor: '#8b5cf6',
  },
  'mobile-gaming': {
    id: 'mobile-gaming',
    name: 'Mobile Gaming',
    description: 'iOS and Android games, tips, and community events.',
    accentColor: '#8b5cf6',
  },
};

// ── Threads, keyed by subforumId — shape mirrors the Thread schema ─────────
export const threadsBySubforum: Record<string, Thread[]> = {
  programming: [
    {
      id: 't1',
      title: 'Read this before posting — Programming forum rules',
      subforumId: 'programming',
      author: users.admin,
      isPinned: true,
      isLocked: true,
      isDeleted: false,
      views: 15240,
      replyCount: 3,
      prefix: 'GUIDE',
      tags: ['rules', 'meta'],
      lastPost: { user: users.admin, createdAt: '3d ago' },
      createdAt: '2025-01-04',
    },
    {
      id: 't2',
      title: 'Why Rust is taking over systems programming',
      subforumId: 'programming',
      author: users.rustacean,
      isPinned: false,
      isLocked: false,
      isDeleted: false,
      views: 8920,
      replyCount: 142,
      prefix: 'DISCUSSION',
      tags: ['rust', 'systems'],
      lastPost: { user: users.rustacean, createdAt: '4m ago' },
      createdAt: '2026-06-10',
    },
    {
      id: 't3',
      title: 'WIP: building a toy compiler in Go, feedback wanted',
      subforumId: 'programming',
      author: users.techguru,
      isPinned: false,
      isLocked: false,
      isDeleted: false,
      views: 1284,
      replyCount: 27,
      prefix: 'WIP',
      tags: ['go', 'compilers'],
      lastPost: { user: users.jonah_dev, createdAt: '38m ago' },
      createdAt: '2026-06-12',
    },
    {
      id: 't4',
      title: 'Best resources to learn algorithms in 2026?',
      subforumId: 'programming',
      author: users.newuser99,
      isPinned: false,
      isLocked: false,
      isDeleted: false,
      views: 642,
      replyCount: 9,
      prefix: 'QUESTION',
      tags: ['algorithms', 'beginners'],
      lastPost: { user: users.rustacean, createdAt: '2h ago' },
      createdAt: '2026-06-14',
    },
    {
      id: 't5',
      title: 'Type inference deep dive: Hindley-Milner explained simply',
      subforumId: 'programming',
      author: users.jonah_dev,
      isPinned: false,
      isLocked: false,
      isDeleted: false,
      views: 3104,
      replyCount: 51,
      prefix: 'GUIDE',
      tags: ['types', 'theory'],
      lastPost: { user: users.techguru, createdAt: '5h ago' },
      createdAt: '2026-06-09',
    },
    {
      id: 't6',
      title: 'Old thread: tabs vs spaces (locked, we know how this ends)',
      subforumId: 'programming',
      author: users.admin,
      isPinned: false,
      isLocked: true,
      isDeleted: false,
      views: 49210,
      replyCount: 891,
      prefix: null,
      tags: ['flamewar'],
      lastPost: { user: users.admin, createdAt: '1y ago' },
      createdAt: '2024-02-01',
    },
  ],
  webdev: [
    {
      id: 't7',
      title: 'Next.js 15 App Router patterns',
      subforumId: 'webdev',
      author: users.jonah_dev,
      isPinned: true,
      isLocked: false,
      isDeleted: false,
      views: 6210,
      replyCount: 64,
      prefix: 'GUIDE',
      tags: ['nextjs', 'react'],
      lastPost: { user: users.jonah_dev, createdAt: '1h ago' },
      createdAt: '2026-05-20',
    },
    {
      id: 't8',
      title: 'CSS container queries — finally usable everywhere?',
      subforumId: 'webdev',
      author: users.techguru,
      isPinned: false,
      isLocked: false,
      isDeleted: false,
      views: 1820,
      replyCount: 33,
      prefix: 'DISCUSSION',
      tags: ['css'],
      lastPost: { user: users.rustacean, createdAt: '20m ago' },
      createdAt: '2026-06-11',
    },
    {
      id: 't9',
      title: 'How do you structure a large monorepo with Turborepo?',
      subforumId: 'webdev',
      author: users.newuser99,
      isPinned: false,
      isLocked: false,
      isDeleted: false,
      views: 410,
      replyCount: 6,
      prefix: 'QUESTION',
      tags: ['monorepo', 'tooling'],
      lastPost: { user: users.jonah_dev, createdAt: '3h ago' },
      createdAt: '2026-06-13',
    },
  ],
  'pc-gaming': [
    {
      id: 't10',
      title: 'Elden Ring DLC tier list — share yours',
      subforumId: 'pc-gaming',
      author: users.pcmasterrace,
      isPinned: false,
      isLocked: false,
      isDeleted: false,
      views: 22310,
      replyCount: 318,
      prefix: 'DISCUSSION',
      tags: ['elden-ring'],
      lastPost: { user: users.pcmasterrace, createdAt: '8m ago' },
      createdAt: '2026-04-15',
    },
    {
      id: 't11',
      title: 'RTX 5090 benchmark thread',
      subforumId: 'pc-gaming',
      author: users.techguru,
      isPinned: true,
      isLocked: false,
      isDeleted: false,
      views: 31840,
      replyCount: 502,
      prefix: 'NEWS',
      tags: ['gpu', 'benchmarks'],
      lastPost: { user: users.techguru, createdAt: '3h ago' },
      createdAt: '2026-01-10',
    },
  ],
};

// Fallback thread generator so unlisted subforums don't render empty during dev.
export function getThreadsForSubforum(subforumId: string): Thread[] {
  return threadsBySubforum[subforumId] ?? [];
}

export function getThreadById(threadId: string): Thread | null {
  for (const threads of Object.values(threadsBySubforum)) {
    const found = threads.find(t => t.id === threadId);
    if (found) return found;
  }
  return null;
}